#!/usr/bin/python3

i = 4
d = 4.0
s = 'HackerRank '
# Declare second integer, double, and String variables.
int2 = None
double2 = None
string2 = ''
# Read and save an integer, double, and String to your variables.
int2 = int(input())
double2 = float(input())
string2 = input()
# Print the sum of both integer variables on a new line.
print(i + int2)
# Print the sum of the double variables on a new line.
print(d + double2)
# Concatenate and print the String variables on a new line
# The 's' variable above should be printed first.
print(s + string2)
