#!/usr/bin/python3
if __name__ == "__main__":
    arr = []
    sumvalue = int()
    result = int()

    for i in range(6):
        arr.append(list(map(int, input().rstrip().split())))
    
    for i in range(4):
        for j in range(4):
            sumvalue = arr[i][j]+arr[i][j+1]+arr[i][j+2]+arr[i+1][j+1]+arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2]
            if sumvalue >= result or (i == 0 and j == 0):
                result = sumvalue

    print(result)
