#!/usr/bin/python3

class Difference:
    def __init__(self, a):
        self.__elements = a

	# Add your code here
    def computeDifference(self):
        abs_array = []
        for i in self.__elements:
            abs_array.append(abs(i))
        max_value = max(abs_array)
        min_value = min(abs_array)
        self.maximumDifference = max_value - min_value

# End of Difference class

_ = input()
a = [int(e) for e in input().split(' ')]

d = Difference(a)
d.computeDifference()

print(d.maximumDifference)
