#!/usr/bin/python3

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class Solution:
    def display(self, head):
        current = head
        while current:
            print(current.data,end=' ')
            current = current.next

    def insert(self, head, data):
        if head == None:
            head = Node(data)
        else:
            cur_node = head
            while cur_node.next != None:
                cur_node = cur_node.next
            cur_node.next = Node(data)
        return head

if __name__ == "__main__":
    mylist= Solution()
    T=int(input())
    head=None
    for i in range(T):
        data=int(input())
        head=mylist.insert(head, data)
    mylist.display(head)
