#!/usr/bin/python3

class Person:
    def __init__(self, initialAge):
        if initialAge >= 0:
            self.age = initialAge
        else:
            self.age = 0
            print("Age is not valid, setting age to 0.")

    def yearPasses(self):
        self.age = self.age + 1

    def amIOld(self):
        if self.age < 13:
            print("You are young.")
        elif self.age in range(13, 18):
            print("You are a teenager.")
        else:
            print("You are old.")

if __name__ == "__main__":
    t = int(input())
    for i in range(0, t):
        initialAge = int(input())
        p = Person(initialAge)
        p.amIOld()
        for j in range(0, 3):
            p.yearPasses()
        p.amIOld()
        print("")

