#!/usr/bin/python3

def factorial():
    integer = int(input())
    result = 1

    for i in range(1, integer + 1):
        result = result * i
    print(result)

if __name__ == "__main__":
    factorial()
